on:
  workflow_call:
    secrets:
      COVERALLS_REPO_TOKEN:
        required: false
      CODECLIMATE_TEST_REPORTER_ID:
        required: false
      NPM_ACCESS_TOKEN:
        required: false

jobs:
  ubuntu-latest-node-lts-ci:
    name: Run continuous integration on Ubuntu Latest with Node LTS
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        registry-url: https://registry.npmjs.org/
    - name: Install dependencies
      run: npm ci
    - name: Prepare code coverage reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: Build
      run: npm run ci
    - name: Upload coverage to coveralls.io
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
      if: (hashFiles('./coverage/') != '') && (env.COVERALLS_REPO_TOKEN != '')
      run: npx coveralls <./coverage/lcov.info
    - name: Upload coverage to codeclimate.com
      env:
        CODECLIMATE_TEST_REPORTER_ID: ${{secrets.CODECLIMATE_TEST_REPORTER_ID}}
      if: (hashFiles('./coverage/') != '') && (env.CODECLIMATE_TEST_REPORTER_ID != '')
      run: |
        ./cc-test-reporter format-coverage --input-type lcov ./coverage/lcov.info
        ./cc-test-reporter upload-coverage --id ${{secrets.CODECLIMATE_TEST_REPORTER_ID}}
    - name: Publish to npmjs.org
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
      if: (env.NODE_AUTH_TOKEN != '') && (github.ref == 'refs/heads/master')
      run: npm publish
    - name: Upload to GitHub Pages
      if: (hashFiles('./github_pages/') != '') && (github.ref == 'refs/heads/master')
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./github_pages
    - name: Deploy to GitHub Pages
      id: deployment
      if: (hashFiles('./github_pages/') != '') && (github.ref == 'refs/heads/master')
      uses: actions/deploy-pages@v4
