# For this workflow to start, in the repository on https://github.com "Settings" -> "Actions" -> "General" ->
# "Actions permissions" must be set accordingly and "Workflow permissions" must be set to "Read and write permissions".
# Sets up an LTS Node.js environment on the latest version of Ubuntu. Then runs `npm ci` followed by `npm run ci`. If
# the folder ./coverage exists, the code coverage data in ./coverage/lcov.info is then uploaded to https://coveralls.io/
# if the associated GitHub repository secret `COVERALLS_REPO_TOKEN` is set. Moreover, if the push happened on the
# `master` branch, the following additional steps are taken:
# - If the secret `NPM_ACCESS_TOKEN` is set, the package is published with `npm publish --provenance`. For prerelease
#   versions (e.g. 1.2.3-beta.4), the identifier between `-` and the last `.` (e.g. `beta`) is used as the npm dist-tag,
#   otherwise `latest` is used. Afterwards, a GitHub release is created for the tag `v<version>` (e.g. v1.2.3), which
#   must already exist in the repository.
# - If the folder ./github_pages exists, the contents are deployed to GitHub Pages. For this to work, "Settings" ->
#   "Pages" -> "Build and deployment" -> "Source" must be set to "GitHub Actions" (currently located on e.g.
#   https://github.com/andreashuber69/node-boilerplate/settings/pages). Also under "Settings" -> "Environments" there
#   must be an environment called "github-pages" where "Deployment branches and tags" allows for deployment from the
#   "master" branch.

on:
  workflow_call:
    secrets:
      COVERALLS_REPO_TOKEN:
        required: false
      CODECLIMATE_TEST_REPORTER_ID:
        required: false
      NPM_ACCESS_TOKEN:
        required: false

jobs:
  ubuntu-latest-node-lts-ci:
    name: Run continuous integration on Ubuntu Latest with Node LTS
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: lts/*
        registry-url: https://registry.npmjs.org/
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run ci
    - name: Upload coverage to coveralls.io
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
      if: (hashFiles('./coverage/') != '') && (env.COVERALLS_REPO_TOKEN != '')
      run: npx coveralls <./coverage/lcov.info
    - name: Set version environment variable
      run: echo "VERSION=v`cat package.json | jq -r '.version'`" >> "$GITHUB_ENV"
    - name: Set tag environment variable
      run: echo "TAG=`echo $VERSION | sed -nE 's/^.*-(.*)\..*$/\1/p'`" >> "$GITHUB_ENV"
    - name: Publish to npmjs.org
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
      if: (env.NODE_AUTH_TOKEN != '') && (github.ref == 'refs/heads/master')
      run: npm publish --tag ${TAG:-latest} --provenance
    - name: Create release on github.com
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
        GH_TOKEN: ${{github.token}}
      if: (env.NODE_AUTH_TOKEN != '') && (github.ref == 'refs/heads/master')
      run: gh release create $VERSION --verify-tag --generate-notes
    - name: Upload to GitHub Pages
      if: (hashFiles('./github_pages/') != '') && (github.ref == 'refs/heads/master')
      uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
      with:
        path: ./github_pages
    - name: Deploy to GitHub Pages
      id: deployment
      if: (hashFiles('./github_pages/') != '') && (github.ref == 'refs/heads/master')
      uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
